---
title: "Cognate-effect Final Report"
author: "Ziyi Bai; Yu Du; Xiaozhou Lu; Jinzhe Zhang"
date: "12/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Abstract

In this project, we explored the "cognate effect" in bilingual aphasia patients. After including the information of patient's accuracy from the information of our client Manuel Marte, we layered the difficulty of the words from 1 to 6 and took each patient's age of acquisition of non native language into consideration. Based on the characteristic of our dataset, we built a logistic regression with random intercept and a multinomial regression with random intercept to interpret the cognate effect. The logistic regression shows that cognate words tend to more likely to be answered correctly and more difficult words tend to have higher level of accuracy. The multinomial models are convergence for all variables. Then, in the following part, we will discuss the results of each model in detail.

### Introduction

Our client, Manuel Marte, is studying Spanish - English bilingual individuals with aphasia and seeks to understand the "cognate effect" for these subject and how it compares with healthy subjects which have been previously studied. Our dataset based on Boston Naming Test: patients are asked to name an object both in English and Spanish. 

We have 26 patients in the dataset, who age from 25 to 80. 22 of them are Spanish dominant patient and 4 of them are English dominant patient. In accuracy column, we coded people correctly name the object into 0 and people incorrectly name the object into 1. In cog column, we coded cognate word into 1 and non-cognate word into 0. In diff column, we leveled our word from difficult 1 to difficult 6 based on the report of gollan2007. Because each patient is unique in our analysis, so we took subject as random intercept. L2AoA indicates the age of a patient acquire the non native language. In language column, 1 means Spanish is this patient's native language and English is non-native language, 0 is the opposite. 

In the following part, we mainly interpret the results of logistic regression and multinomial regression. 


### Logistic Regression





### Multinomial Regression





### Conclusion

We tried logistic regression. We still divide the data into two groups: Spanish and English. We first included only cognate as the only factor, as our baseline to find the optimal model by comparing it. By using the glmer package, we divide the words into different subject levels. When the words are in English and have the same difficulty level, cognate words will have a higher probability (94.43% higher) to answer correctly. When the words are in Spanish and the difficulty level is the same, cognate words will have a higher probability (76.195.% higher) to answer correctly.

Before the fit model, we processed the missing data in the data, and explored the influence of Spanish and English cognate words on the accuracy rate. We divided the data of all subjects into four categories, 1. Spanish and English is correct, 2. Spanish is correct, English is wrong, 3. Spanish is wrong, and English is correct. 4. Both languages are wrong. At the same time, considering the differences of each participant to words, we will use random intercept to express this phenomenon. Our group fits three mutinomial equations, and compares the influence of cognate words through the LOO equation. In the first equation, our group did not include any demographic information. We will use it as a baseline to compare with other models to arrive at a relatively optimal model. In b4, we included demographic information AOA and language as variables. We use cognate as the independent variable and the probability of being correct as the dependent variable. It can be seen that with the inclusion of demographic data, as the degree of cognate becomes stronger, the possibility of simultaneous errors in two languages gradually decreases. The probability that the pair and all are correct gradually rises. Therefore, according to the results of the graph, we can conclude that the influence of cognate has a positive influence on the correctness rate. When we replace cognate with difficulty, the possibility of correctness decreases as the difficulty increases, and the possibility of error increases, which is in line with our expectations. It also proved the reliability of the model.


Therefore, from the above regression model, we can see that the influence of cognate on the correct green is still very significant. Of course, our research still has certain limitations, such as insufficient data and insufficient diversity and comprehensiveness in the optimization and comparison of models.






















