---
title: "Model"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("lme4")
```

```{r}
library(dplyr)
eng<-read.csv("eng.csv")
#eng
spa<-read.csv("spa.csv")
#spa
```

```{r}
#44 items labeled as cognate/noncognate.
eng1<-eng%>%filter(!word %in% c('bed','tree', 'pencil', 'house', 'whistle','scissors','saw','toothbrush','pretzel','bench','globe','cactus','escalator','pelican',
                              'stethoscope','palette'))
#eng1

```

```{r}
#code： cognate=1, noncognate=0.
eng1$cognate[eng1$word %in% c('comb','broom','octopus','mushroom','hanger','wheelchair','snail','seahorse','wreath',
'beaver','stilts','acorn','knocker','muzzle','funnel','noose','latch','scroll','tongs','yoke','trellis','protractor')] <- 0
eng1$cognate[!eng1$word %in% c('comb','broom','octopus','mushroom','hanger','wheelchair','snail','seahorse','wreath',
'beaver','stilts','acorn','knocker','muzzle','funnel','noose','latch','scroll','tongs','yoke','trellis','protractor')] <- 1
eng1
write.csv(eng1,"eng1.csv",row.names=FALSE)
```

```{r}
#44 items labeled as cognate/noncognate.
spa1<-spa%>%filter(!word %in% c('bed','tree', 'pencil', 'house', 'whistle','scissors','saw','toothbrush','pretzel','bench','globe','cactus','escalator','pelican',
                              'stethoscope','palette'))
#spa1
```

```{r}
#code： cognate=1, noncognate=0.
spa1$cognate[spa1$word %in% c('comb','broom','octopus','mushroom','hanger','wheelchair','snail','seahorse','wreath',
'beaver','stilts','acorn','knocker','muzzle','funnel','noose','latch','scroll','tongs','yoke','trellis','protractor')] <- 0
spa1$cognate[!spa1$word %in% c('comb','broom','octopus','mushroom','hanger','wheelchair','snail','seahorse','wreath',
'beaver','stilts','acorn','knocker','muzzle','funnel','noose','latch','scroll','tongs','yoke','trellis','protractor')] <- 1
spa1
write.csv(spa1,"spa1.csv",row.names=FALSE)
```

```{r}
#logistic regression model for english data:
M1<-glm(accuracy~cognate, family=binomial(link="logit"),data=eng1)
summary(M1)
```

invlogit(-0.56+0.33*1)=0.44
invlogit(-0.56)=0.36


```{r}
#logistic regression model for spanish data:
M2<-glm(accuracy~cognate, family=binomial(link="logit"),data=spa1)
summary(M2)
```

invlogit(-1.23+0.69*1)=0.37
invlogit(-1.23)=0.23


## Add random variable into logistic model 
```{r}
M3 <- lmer(accuracy~(1|cognate),data=eng1)
print(M3)
```

```{r}
M4 <- lmer(accuracy~(1|cognate),data=spa1)
print(M4)
```

##add difficult into dataset
```{r}
spa2 <- read.csv("spa1.csv",header = T)
eng2 <- read.csv("eng1.csv",header = T)
eng2$diff <- as.numeric(eng2$diff)
spa2$diff <- as.numeric(spa2$diff)
```

## refit model 
```{r}
M5 <- glmer(accuracy~(1|cognate)+diff,data=eng2)
print(M5)
M6 <- glmer(accuracy~(1|cognate)+diff,data=spa2)
print(M6)
```



